SueldosYjornales/Controllers/EmpleadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SueldosYjornales.Controllers {
    [Authorize(Roles = "Padrones,Operador,Admin,Supervisor,LiquidadorSalario")]
    public class EmpleadosController : Controller {
        // GET: Empleados
        public ActionResult Index() {
            return View();
        }

        // GET: Empleados/Details/5
        public ActionResult Details(int id) {
            ViewBag.empleadoID = id;
            return View();
        }

        // GET: Empleados/Historicos/5
        public ActionResult Historicos(int id) {
            ViewBag.empleadoID = id;
            return View();
        }

        // GET: Empleados/Resumen/5
        public ActionResult Resumen(int id) {
            ViewBag.empleadoID = id;
            return View();
        }

        public ActionResult SubirImagenes(int id) {
            ViewBag.empleadoID = id;
            return View();
        }
        public ActionResult ImprimirCedula(int id) {
            ViewBag.empleadoID = id;
            return View();
        }
    }
}

SueldosYjornales/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SueldosYjornales.Controllers {   
    public class HomeController : Controller {
        public ActionResult Index() {
            return View();
        }
        [Authorize(Roles="Operador")]
        public ActionResult Menu() {
            return View();
        }

        public ActionResult About() {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact() {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SueldosYjornales/Controllers/LiquidacionSalariosController.cs
using Newtonsoft.Json;
using SYJ.Application.Dto.Auxiliares;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SueldosYjornales.Controllers
{
     [Authorize(Roles = "LiquidadorSalario")]
    public class LiquidacionSalariosController : Controller
    {
        // GET: LiquidacionSalarios
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ImpresionLiqSalarios(string jsonInput) {
            ViewBag.flDto = jsonInput;
            return View();
        }
        public ActionResult ImpresionLiqAguinaldo(string jsonInput) {
            ViewBag.flDto = jsonInput;
            return View();
        }
        public ActionResult ImpresionLiqAguinaldoReporte(string jsonInput) {
            ViewBag.flDto = jsonInput;
            return View();
        }
    }
}

SueldosYjornales/Controllers/PrestamosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SueldosYjornales.Controllers
{
    public class PrestamosController : Controller
    {
        // GET: Prestamos
        public ActionResult Index()
        {
            return View();
        }
    }
}

SueldosYjornales/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section scripts{
    <script src="~/Scripts/Empleados/Index/Services/common.services.js"></script>
    <script type="text/javascript">
        (function () {
            'use strict';
            angular
                .module('sueldosYjornalesApp')
                .factory('sYjResource', sYjResource);

            sYjResource.$inject = ['$resource'];

            function sYjResource($resource) {
                var empleados = $resource("@Href("~/api/Empleados")");
                var ubicacionSucUsuarios = $resource("@Href("~/api/UbicacionSucUsuarios")");

                return {
                    "empleados": empleados,
                    "ubicacionSucUsuarios": ubicacionSucUsuarios
                }
            }
        })();
    </script>
}
<div class="jumbotron">
    <h1>Sueldos y Jornales</h1>
    <p class="lead">Esta aplicacion controlara los sueldos y jornales, con informes adecuados a los requisitos que tiene el Ministerio de Justicia y Trabajo y el I.P.S.</p>    
</div>

@*<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>*@

SueldosYjornales/Views/Home/Menu.cshtml
@{
    ViewBag.Title = "Menu";
}
@section scripts{
    <script src="~/Scripts/Home/Menu/Services/common.services.js"></script>
    <script src="~/Scripts/Home/Menu/Controllers/ubicacionSucUsuarioCtrl.js"></script>
    <script type="text/javascript">
        (function () {
            'use strict';
            angular
                .module('sueldosYjornalesApp')
                .factory('sYjResource', sYjResource);

            sYjResource.$inject = ['$resource'];

            function sYjResource($resource) {
                var empresas = $resource("@Href("~/api/Empresas")");
                var sucursales = $resource("@Href("~/api/Sucursales")");
                var sucursalesSegunEmpresaID = $resource("@Href("~/api/Sucursales/SegunEmpresaID")");
                var empresas = $resource("@Href("~/api/Empresas")");
                var ubicacionSucUsuarios = $resource("@Href("~/api/UbicacionSucUsuarios")");

                return {
                    "empresas": empresas,
                    "Sucursales": sucursales,
                    "sucursalesSegunEmpresaID": sucursalesSegunEmpresaID,
                    "ubicacionSucUsuarios": ubicacionSucUsuarios
                }
            }
        })();
    </script>
}

<div class="container" style="margin-top:25px;" ng-controller="ubicacionSucUsuarioCtrl" ng-cloak>
    <div class="panel panel-primary">
        <div class="panel-heading">
            Sucursal de trabajo
            <span class="badge">
                {{ubicacionSucUsuario.empresa.nombreEmpresa | uppercase}} -
                {{ubicacionSucUsuario.sucursale.nombreSucursal | uppercase}}
            </span>
        </div>
        <div class="panel-body">
            <form class="form-inline" name="ubicacionSucUsuariosForm">
                <div class="form-group">
                    <label for="empresa">Empresa</label>
                    <select name="moneda" required
                            ng-model="ubicacionSucUsuario.empresa"
                            ng-options="r.nombreEmpresa for r in empresas" class="form-control"
                            ng-required="true">
                        <!--<option value="">-- Seleccione el concepto --</option>-->
                        <option value="" ng-hide="ubicacionSucUsuario.empresa">Seleccione empresa</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="sucursale">Sucursal</label>
                    <select name="moneda" required
                            ng-model="ubicacionSucUsuario.sucursale"
                            ng-options="r.nombreSucursal for r in sucursales" class="form-control"
                            ng-required="true">
                        <!--<option value="">-- Seleccione el concepto --</option>-->
                        <option value="" ng-hide="ubicacionSucUsuario.sucursale">Seleccione sucursal</option>
                    </select>

                </div>
                <div class="form-group">
                    <label for="sucursale" style="display:block">Seleccionar</label>
                    <button ng-click="guardar()" ng-disabled="ubicacionSucUsuariosForm.$invalid" class="btn btn-default">
                        Sucursal
                    </button>
                </div>
                <div class="form-group" ng-show="mensajeDelServidor != null" style="margin-left:25px;">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            {{mensajeDelServidor}}
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="row">
            <div class="col-md-6">

            </div>
            <div class="col-md-6">

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center">Menu sueldos y jornales</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="thumbnail">
                <a href="@Url.Action("Index", "Empleados")">
                    <img src="~/Images/empleados.JPG" class="img-rounded  img-responsive" />
                </a>
                <div class="caption">
                    <h3 style="text-align:center;">Empleados</h3>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <a href="@Url.Action("Index", "LiquidacionSalarios")">
                    <img src="~/Images/Liquidar-Salarios.gif" class="img-rounded  img-responsive" />
                </a>
                <div class="caption">
                    <h3 style="text-align:center;">Liquidacion de salarios/aguinaldos</h3>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <a href="@Url.Action("Index", "Prestamos")">
                    <img src="~/Images/Prestamos.jpg" class="img-rounded  img-responsive" />
                </a>
                <div class="caption">
                    <h3 style="text-align:center;">Prestamos</h3>
                </div>
            </div>
        </div>
    </div>
</div>